---
title: "pivot_lobsters.Rmd"
author: "Katie Maddox"
date: "1/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## attach libraries
library(tidyverse)
library(readxl)
library(here) 
library(skimr) #install.packages('skimr')
library(kableExtra)  #install.packages('kableExtra')
```
```{r}
## read in data
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)
# explore data
skimr::skim(lobsters) 
#you get the same thing if you exclude "skimr::". It is simply an annotation to show where skim() is from.
```
```{r}
#Now we take our data, group by year and summarize by count.
lobsters %>%
  group_by(year) %>%
  summarize(count_by_year = n())
#our own lil pivot table!
```

```{r}
#group by multiple variables
lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(),
            mean_size_mm = mean(size_mm))
#if we have NA in our data, it can cuase the summary in our pivot table to be NA, so we can have R ignore those NAs using na.rm(TRUE)
lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm=TRUE), 
            sd_size_mm = sd(size_mm, na.rm=TRUE))
#now we're saving the pivot table as a variable so we can utilize it later
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm = TRUE), 
            sd_size_mm = sd(size_mm, na.rm = TRUE))
#let's make a table with that new variable
siteyear_summary %>%
  kable()
#beautiful
```
```{r}
#ACTIVITY, my turn here we go...

#Build from our analysis and calculate the median lobster size for each site year. Your calculation will use the size_mm variable and function to calculate the median (Hint: ?median)
#2create and ggsave() a plot.
activity_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            median_size_mm = median(size_mm, na.rm = TRUE),
  )
#calculated median size, grouped by site and year
activity_summary %>%
  kable()
#shows me summary of my pivot table
```
```{r}
ggplot(data = activity_summary, aes(x=year, y=median_size_mm, color=site)) +geom_line() + theme_minimal() +
  labs(
    x = "Year",
    y = "Median",
    title = "Median Lobster Size by Site",
    subtitle = "(2012 - 2016)")
```
```{r}
#save it
ggsave(here("figures", "lobsters-line.png"))
```
```{r}
#can also use a count function
lobsters %>%
  count(site, year)
#using Mutate, we can add a column to a dataset, like calculating meters from milimeters
lobsters %>%
  mutate(size_m = size_mm / 1000)
#we can see the calculated column has been added to the right side of our rectangle of data

#in the chunk below, we added two columns with set values (millenia and observer) and created a new dataset kinda
lobsters_detailed <- lobsters %>%
  mutate(size_m = size_mm / 1000, 
         millenia = 2000,
         observer = "Allison Horst")
```
```{r}
#sometimes we only want to present datasets with some of the data, we can do this using the select() function
lobsters_detailed %>%
  select(date, site, size_m)
```

